import { describe, expect, it } from 'vitest';
import { nextSubscriptionPeriodEnd, shouldRenewStripeInvoice } from '@/lib/payments';

describe('subscription renewal helpers', () => {
  it('extends an active subscription from its current end date', () => {
    expect(nextSubscriptionPeriodEnd('2026-10-15T10:00:00.000Z', new Date('2026-09-10T10:00:00.000Z')).toISOString())
      .toBe('2026-11-15T10:00:00.000Z');
  });

  it('extends an expired subscription from the current date', () => {
    expect(nextSubscriptionPeriodEnd('2026-08-15T10:00:00.000Z', new Date('2026-09-10T10:00:00.000Z')).toISOString())
      .toBe('2026-10-10T10:00:00.000Z');
  });

  it('does not renew the invoice generated by the initial checkout', () => {
    expect(shouldRenewStripeInvoice('subscription_create')).toBe(false);
    expect(shouldRenewStripeInvoice('subscription_cycle')).toBe(true);
  });
});
